TypeOfFood = input("Name a Food ")
TypeOfPlant = input("Name a Plant ")
CookingMethod = input("Name Method of Cooking ")
BurnFood = input("Word to describe Burned Food ")
HouseholdItem = input("Name a Household Item ")
print()
print("MENU")
print(CookingMethod)
print(TypeOfFood)
print("with",BurnFood,TypeOfPlant)
print("on a bed of",HouseholdItem)