TypeOfStarter = input("name of starter ")
ServedOn = input("What is your starter served on ")
TypeOfFood = input("Name a Food ")
TypeOfPlant = input("Name a Plant ")
CookingMethod = input("Name Method of Cooking ")
BurnFood = input("Word to describe Burned Food ")
HouseholdItem = input("Name a Household Item ")
TypeOfPudding = input("name of a dessert ")
TypeOfSauce = input("name of sauce on dessert ")
ServedWith = input("what dessert is served with ")
print()
print("==MENU==")
print()
print("==STARTER==")
print()
print(TypeOfStarter)
print(ServedOn)
print()
print("==DINNER==")
print()
print(CookingMethod)
print(TypeOfFood)
print("with",BurnFood,TypeOfPlant)
print("on a bed of",HouseholdItem)
print("==DESSERT==")
print("a delicious",TypeOfPudding)
print("Drizzled with", TypeOfSauce)
print("and",ServedWith)
